# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 09:51
from __future__ import unicode_literals

from django.db import migrations, models


def change_to_date(apps, schema_editor):
    Menu = apps.get_model("menu", "menu")
    for menu in Menu.objects.all():
        menu.created_date_new = menu.created_date.date()
        menu.save()


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20160711_0552'),
    ]

    operations = [
        migrations.AddField("Menu", "created_date_new",
                            models.DateField(blank=True, null=True)),
        migrations.RunPython(change_to_date),
        migrations.RemoveField("Menu", "created_date"),
        migrations.RenameField("Menu", "created_date_new", "created_date")
    ]
